name = "hport-api"
main = "index.js"
compatibility_date = "2024-01-19"

[vars]
# Environment variables (Fill in your real IDs or configure via Dashboard)
CF_ACCOUNT_ID = ""
CF_ZONE_ID = ""
# CF_API_TOKEN should be set as a Secret (See GUIDE.md)
