name = "hport-api"
main = "index.js"
compatibility_date = "2024-01-19"

[vars]
# Các biến môi trường (Bạn sẽ điền ID thật vào đây hoặc cấu hình qua Dashboard)
CF_ACCOUNT_ID = ""
CF_ZONE_ID = ""
# CF_API_TOKEN nên được đặt làm Secret (Hướng dẫn bên dưới)
